/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * The schema version for this configuration file. Must be a valid schema version.
   */
  $schema?: string;
  /**
   * The command to execute the script, must include the placeholder '${post}' and can have any file extension or none.
   */
  execScriptCommand: string;
  /**
   * The output directory for the generated migrations. Must be a valid directory path.
   */
  outputDir: string;
  /**
   * The directory where migrations are stored. Must be a valid directory path.
   */
  migrationsDir: string;
  /**
   * Temporary directory for processing. Must be a valid directory path.
   */
  tempDir: string;
  /**
   * The filename for prisma schema files within migration directories.
   */
  migrationSchemaFileName: string;
  /**
   * Log level for the script, must be one of 'info', 'debug', or 'error'.
   */
  log: "none" | "info" | "verbose";
}
